### PR TITLE
Create meeting sequence step 1 - Set meeting name and add guests

### PR DESCRIPTION
**Pull request by anna-giang**
Add a page to allow users to set a meeting name and add meeting guests when they create a meeting.

### CODE REVIEW

**Comment by anna-giang** [comment]
I accidentally rebased my branch onto master, which is why there is two copies of each commit and the 'Merge branch...' commit (sorry! 😅)

**Comment by theresenieva** [comment]
LGTM

**Review by theresenieva — COMMENTED** [review]
LGTM. I used git reset to remove unwanted commits from my branch, maybe that could be useful for you?

**Review by vivianho18 — COMMENTED** [review]
LGTM - only thing is I don't think you need to bother too much with user input checks at the moment for the prototype.

**Review by BipBopBoop — APPROVED** [review]
lgtm

**Pull request merged**
